app/game/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError, IntegerField, DecimalField, SelectField
from wtforms.validators import DataRequired, Email, EqualTo
from flask_wtf.file import FileField, FileAllowed, FileRequired

# from ..models import Employee
from ..database.genres import Genres
from ..database.series import Series

class CreateGame(FlaskForm):
    """
    Form for create game
    """
    # form
    genres = Genres()
    series = Series()

    name = StringField('Name', validators=[DataRequired()])
    score_critics = DecimalField('Score', validators=[DataRequired()])
    genres_id = SelectField('Genre', choices=[(genre['id'], genre['name']) for genre in genres.all()], validators=[DataRequired()], coerce=int)
    series_id = SelectField('Series', choices=[(serie['id'], serie['name']) for serie in series.all()], coerce=int)
    # art = FileField('Image File', validators=[FileAllowed(['jpg', 'png'], 'Images only!')])

    submit = SubmitField('Submit')

app/game/__init__.py
# app/auth/__init__.py

from flask import Blueprint

game = Blueprint('game', __name__)

from . import views

app/game/views.py
import os
import base64
from flask import flash, redirect, render_template, url_for
from werkzeug.utils import secure_filename
# from flask_login import login_required

from . import game
from .forms import CreateGame
from ..database.games import Games


@game.route('/games')
def index():
    """
    Render the index template
    """
    games = Games()
    print(games.all())
    return render_template('game/index.html', title="Index", games=games.all())


@game.route('/games/new', methods=['GET', 'POST'])
def new():
    """
    Render the new template
    """

    add_game = True

    form = CreateGame()
    if form.validate_on_submit():

      # filename = secure_filename(form.art.data.filename)
      # form.art.data.save('uploads/' + filename)

      game = {
          "name": form.name.data,
          "score_critics": float(form.score_critics.data),
          "genres_id": form.genres_id.data,
          "series_id": form.series_id.data,
          # "art": base64.b64encode(bytes(str(form.art.data.read()), 'utf-8'))
      }
      print(game)
      new_game = Games()
      new_game.create(**game)
      # form.art.data.save('../static/images/' + form.art.data.filename)
      try:
        print("hello")
        # add employee to the database
        flash('You have successfully created a Game.')
      except:
        # in case department name already exists
        flash('Error: game already exists.')

      # redirect to the login page
      return redirect(url_for('game.index'))

    return render_template('game/new.html', action="Add", add_game=add_game, form=form, title="Add Game")


@game.route("/game/edit/<int:id>", methods=['GET', 'POST'])
def edit_game(id):
    """
    Edit a game
    """

    add_game = False

    cur = Games()
    game = cur.select(id)
    try:
      form = CreateGame(obj=game)
    except:
      print("Cant find game.")

    if form.validate_on_submit():
        game["name"] = form.name.data
        game["score_critics"] = float(form.score_critics.data)
        game["genres_id"] = form.genres_id.data
        game["series_id"] = form.series_id.data
        game["art"] = 'NULL'
        print(game)
        cur.update(**game)

        flash('You have successfully edited a game.')

        # redirect to the departments page
        return redirect(url_for('game.index'))

    form.name.data = game["name"]
    form.score_critics.data = game["score_critics"]
    form.genres_id.data = game["genres_id"]
    form.series_id.data = game["series_id"]
    
    return render_template('game/new.html', action="Edit",
                           add_game=add_game, form=form,
                           game=game, title="Edit Game")


@game.route("/game/delete/<int:id>", methods=['GET', 'POST'])
def delete_game(id):
  """
    Delete a game from the database
  """
  game = Games()
  try:
    game.delete(id)
    flash('You have successfully deleted the game.')
  except:
    print("Cant delete game.")

  # redirect to the departments page
  return redirect(url_for('game.index'))

  return render_template(title="Delete Department")

app/templates/game/index.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Games{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Games</h1>
        {% if games %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="20%"> Name </th>
                  <th width="15%"> Score </th>
                  <th width="20%"> Genre </th>
                  <th width="15%"> Series </th>
                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for game in games %}
                <tr>
                  <td> {{ game.name }} </td>
                  <td> {{ game.score_critics }} </td>
                  <td> {{ game.genres_id }} </td>
                  <td> {{ game.series_id }} </td>
                  <td>
                    <a href="{{ url_for('game.edit_game', id=game.id) }}">
                      <i class="fa fa-pencil"></i> Edit 
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('game.delete_game', id=game.id) }}">
                      <i class="fa fa-trash"></i> Delete 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No games have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('game.new') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Game
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/game/new.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_game %}
        Add Game
    {% else %}
        Edit Game
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_game %}
                <h1>Add game</h1>
            {% else %}
                <h1>Edit game</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}