app/dog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError, IntegerField
from wtforms.validators import DataRequired, Email, EqualTo

# from ..models import Employee


class CreateDog(FlaskForm):
    """
    Form for create dog
    """

    name = StringField('Name', validators=[DataRequired()])
    age = IntegerField('Age', validators=[DataRequired()])

    # email = StringField('Email', validators=[DataRequired(), Email()])
    # username = StringField('Username', validators=[DataRequired()])
    # first_name = StringField('First Name', validators=[DataRequired()])
    # last_name = StringField('Last Name', validators=[DataRequired()])
    # password = PasswordField('Password', validators=[
    #                                     DataRequired(),
    #                                     EqualTo('confirm_password')
    #                                     ])
    # confirm_password = PasswordField('Confirm Password')
    submit = SubmitField('Submit')

    # def validate_email(self, field):
    #     if Employee.query.filter_by(email=field.data).first():
    #         raise ValidationError('Email is already in use.')

    # def validate_username(self, field):
    #     if Employee.query.filter_by(username=field.data).first():
    #         raise ValidationError('Username is already in use.')


class LoginForm(FlaskForm):
    """
    Form for users to login
    """
    # email = StringField('Email', validators=[DataRequired(), Email()])
    # password = PasswordField('Password', validators=[DataRequired()])
    # submit = SubmitField('Login')

app/dog/__init__.py
# app/auth/__init__.py

from flask import Blueprint

dog = Blueprint('dog', __name__)

from . import views

app/dog/views.py
from flask import flash, redirect, render_template, url_for
# from flask_login import login_required

from . import dog
from .forms import CreateDog
from ..database.dogs import Dogs


@dog.route('/dogs')
def index():
    """
    Render the index template
    """
    dogs = Dogs()
    print(dogs.all())
    return render_template('dog/index.html', title="Index", dogs=dogs.all())


@dog.route('/dogs/new', methods=['GET', 'POST'])
def new():
    """
    Render the new template
    """

    add_dog = True

    form = CreateDog()
    if form.validate_on_submit():

      try:
        dogo = {
          "name": form.name.data,
          "age": form.age.data
        }
        print(dogo)
        new_dog = Dogs()
        new_dog.create(**dogo)
        
        # add employee to the database
        flash('You have successfully created a Dog.')
      except:
        # in case department name already exists
        flash('Error: dog already exists.')
      

      # redirect to the login page
      return redirect(url_for('dog.index'))

    return render_template('dog/new.html', action="Add", add_dog=add_dog, form=form, title="Add Dog")

@dog.route("/dog/edit/<int:id>", methods=['GET', 'POST'])
def edit_dog(id):
    """
    Edit a dog
    """

    add_dog = False

    cur = Dogs()
    dog = cur.select(id)
    try:
      form = CreateDog(obj=dog)
    except:
      print("Cant find dog.")

    if form.validate_on_submit():
        dog["name"] = form.name.data
        dog["age"] = form.age.data
        cur.update(**dog)

        flash('You have successfully edited a dog.')

        # redirect to the departments page
        return redirect(url_for('dog.index'))
    
    form.age.data = dog["age"]
    form.name.data = dog["name"]
    return render_template('dog/new.html', action="Edit",
                           add_dog=add_dog, form=form,
                           dog=dog, title="Edit Dog")

@dog.route("/dog/delete/<int:id>", methods=['GET', 'POST'])
def delete_dog(id):
  """
    Delete a dog from the database
  """
  dog = Dogs()
  try:
    dog.delete(id)
    flash('You have successfully deleted the dog.')
  except:
    print("Cant delete dog.")

  # redirect to the departments page
  return redirect(url_for('dog.index'))

  return render_template(title="Delete Department")

app/templates/dog/index.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Dogs{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Dogs</h1>
        {% if dogs %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="30%"> Name </th>
                  <th width="40%"> Age </th>
                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for dog in dogs %}
                <tr>
                  <td> {{ dog.name }} </td>
                  <td> {{ dog.age }} </td>
                  <td>
                    <a href="{{ url_for('dog.edit_dog', id=dog.id) }}">
                      <i class="fa fa-pencil"></i> Edit 
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('dog.delete_dog', id=dog.id) }}">
                      <i class="fa fa-trash"></i> Delete 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No dogs have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('dog.new') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Dog
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/dog/new.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_dog %}
        Add Dog
    {% else %}
        Edit Dog
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_dog %}
                <h1>Add dog</h1>
            {% else %}
                <h1>Edit dog</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}