app/review/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError, IntegerField, SelectField, DecimalField
from wtforms.validators import DataRequired, Email, EqualTo

# from ..models import Employee

from ..database.games import Games
from app.models import User

class CreateReview(FlaskForm):
    """
    Form for create review
    """

    users = User()
    games = Games()

    score = DecimalField('Score', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    game_id = SelectField('Game', choices=[(game['id'], game['name']) for game in games.all()], validators=[DataRequired()], coerce=int)
    users_id = SelectField('User', choices=[(user['id'], user['first_name']) for user in users.all()], validators=[DataRequired()], coerce=int)

    submit = SubmitField('Submit')

app/review/__init__.py
# app/auth/__init__.py

from flask import Blueprint

review = Blueprint('review', __name__)

from . import views

app/review/views.py
from flask import flash, redirect, render_template, url_for
# from flask_login import login_required

from . import review
from .forms import CreateReview
from ..database.reviews import Reviews


@review.route('/reviews')
def index():
    """
    Render the index template
    """
    reviews = Reviews()
    print(reviews.all())
    return render_template('review/index.html', title="Index", reviews=reviews.all())


@review.route('/reviews/new', methods=['GET', 'POST'])
def new():
    """
    Render the new template
    """

    add_review = True

    form = CreateReview()
    if form.validate_on_submit():

      try:
        review = {
          "score": float(form.score.data),
          "description": form.description.data,
          "games_id": form.game_id.data,
          "users_id": form.users_id.data
        }

        print(review)
        new_review = Reviews()
        new_review.create(**review)
        
        # add employee to the database
        flash('You have successfully created a Review.')
      except:
        # in case department name already exists
        flash('Error: review already exists.')
      

      # redirect to the login page
      return redirect(url_for('review.index'))

    return render_template('review/new.html', action="Add", add_review=add_review, form=form, title="Add Review")

@review.route("/review/edit/<int:id>", methods=['GET', 'POST'])
def edit_review(id):
    """
    Edit a review
    """

    add_review = False

    cur = Reviews()
    review = cur.select(id)
    try:
      form = CreateReview(obj=review)
    except:
      print("Cant find review.")

    if form.validate_on_submit():
        review["score"] = float(form.score.data)
        review["description"] = form.description.data
        review["games_id"] = form.game_id.data
        review["users_id"] = form.users_id.data
        cur.update(**review)

        flash('You have successfully edited a review.')

        # redirect to the departments page
        return redirect(url_for('review.index'))
    
    form.score.data = review["score"]
    form.description.data = review["description"]
    form.game_id.data = review["games_id"]
    form.users_id.data = review["users_id"]
    return render_template('review/new.html', action="Edit",
                           add_review=add_review, form=form,
                           review=review, title="Edit Review")

@review.route("/review/delete/<int:id>", methods=['GET', 'POST'])
def delete_review(id):
  """
    Delete a review from the database
  """
  review = Reviews()
  try:
    review.delete(id)
    flash('You have successfully deleted the review.')
  except:
    print("Cant delete review.")

  # redirect to the departments page
  return redirect(url_for('review.index'))

  return render_template(title="Delete Department")

app/templates/review/index.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Reviews{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Reviews</h1>
        {% if reviews %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="10%"> Score </th>
                  <th width="30%"> Descripton </th>
                  <th width="15%"> Games </th>
                  <th width="15%"> Users </th>
                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for review in reviews %}
                <tr>
                  <td> {{ review.score }} </td>
                  <td> {{ review.description }} </td>
                  <td> {{ review.games_id }} </td>
                  <td> {{ review.users_id }} </td>
                  <td>
                    <a href="{{ url_for('review.edit_review', id=review.id) }}">
                      <i class="fa fa-pencil"></i> Edit 
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('review.delete_review', id=review.id) }}">
                      <i class="fa fa-trash"></i> Delete 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No reviews have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('review.new') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Review
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/review/new.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_review %}
        Add Review
    {% else %}
        Edit Review
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_review %}
                <h1>Add review</h1>
            {% else %}
                <h1>Edit review</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}